<table cellpadding="0" cellspacing="0" border="0" width="645">
<tr>
 <td valign="top" background="images/freeshipping.gif">
  <img src="images/spacer.gif" border="0" height="20" width="280" alt=""><br>
  <img src="images/spacer.gif" border="0" height="55" width="21" alt=""> 
  <table >
   <tr>
    <td>
     <img src="images/spacer.gif" border="0" height="20" width="124" alt="">
    </td>

    <td><b>
       <span class="body-headline-gold">
         Limited time offer<br>
       </span></b>
       <span class="home-main-text">Receive free shipping on purchases of any Muffler.<br>
       </span>
    </td>
   </tr>
  </table>
 </td>
 <td>
 <html:link page="/action/viewitemdetail?id=116"> 
   <html:img page="/multimedia/mufflers.gif" width="96" height="85" border="0" alt="Mufflers"/><br>
  </html:link>
  </td>
  <td valign="top" width="108" align="right"><br>
     <table width="90" border="0" cellpadding="0" cellspacing="0" align="right">
	<tr>
	 <td colspan="5"><img src="images/featured_dept.gif"></td>
	</tr>
	<tr>
	  <td width="1"><img src="images/spacer.gif" border="0" height="1" width="1" alt=""></td>
  	  <td width="1"><img src="images/spacer.gif" border="0" height="1" width="1" alt=""></td>
	  <td width="5"><img src="images/spacer.gif" border="0" height="1" width="5" alt=""></td>
	  <td width="83"><span class="feature-dept-text" style="font-size: 10px;">
           <img src="images/spacer.gif" border="0" height="5" width="83" alt="">
           
           <br>Tires<br></span>
         <span class="feature-dept-text" style="font-size: 10px;">
         
              <img src="images/spacer.gif" border="0" height="5" width="83" alt="">
              
              <br>Valve Covers<br></span>
              <span class="feature-dept-text" style="font-size: 10px;">
               <img src="images/spacer.gif" border="0" height="5" width="83" alt="">
               
               <br>Carborators<br>
              </span>
              <span class="feature-dept-text" style="font-size: 10px;">
               <img src="images/spacer.gif" border="0" height="5" width="83" alt=""><br>
                 Water Pumps<br>
             </span>
             <span class="feature-dept-text" style="font-size: 10px;">
            <img src="images/spacer.gif" border="0" height="5" width="83" alt=""><br>
             Cam Shafts<br></span>
              <span class="feature-dept-text" style="font-size: 10px;">
               <img src="images/spacer.gif" border="0" height="5" width="83" alt=""><br>
             Exhaust Pipes<br></span>       
		</td>
	<td width="1"><img src="images/spacer.gif" border="0" height="1" width="2" alt=""></td>
	</tr>
</table>
</td>
</tr>
</table>