<table border="0" width="100%" cellspacing="0" cellpadding="0">
 <tr>
  <td width="135" bgcolor="#EEFFFF" nowrap><nobr>
   <html:img page="/images/spacer.gif" width="10" height="5" border="0" alt=""/>
     
    <html:img altKey="navbar.home.image.alt" bundle="IMAGE_RESOURCE_KEY" pageKey="navbar.home.image" width="125" height="15" border="0"/>
     

</nobr>
  </td>
  <td width="480" bgcolor="#DADAFF" align="left" nowrap>   
    <html:img altKey="navbar.home.image.alt" bundle="IMAGE_RESOURCE_KEY" pageKey="navbar.main.image" width="480" height="15" border="0" usemap="#navTopMap"/>   
  </td>
  <td width="165" bgcolor="#DADAFF" nowrap>
    <html:img page="/images/spacer.gif" width="165" height="8" border="0" alt=""/>
  </td>
  <td width="100%" bgcolor="#DADAFF" nowrap>
   <html:img page="/images/spacer.gif" width="1" height="1" border="0" alt=""/>
  </td>
 </tr>
</table>
